language: python
sudo: false
python:
- '2.7'
# addons:
#   postgresql: "9.3"

# cache:
#   directories:
#   - $HOME/.pip-cache/

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
- flake8 convergence/
- flake8 blog/
- coverage run --source=junction --omit='*tests*,*commands*,*migrations*,*admin*,*wsgi*' -m py.test -v --tb=native
- coverage report

after_success:
  coveralls

# notifications:
#   email:
#     on_success: change  # [always|never|change]
#     on_failure: always  # [always|never|change]
